### ISSUE TITLE
vue-stylus errors preveting startup

### ISSUE THREAD

**Issue by AsafAgranat** [Akryum/vue-meteor-demo#12]
This is from the demo clone - no changes made.
demo cloned on a new windows machine with node 6.11.2.
On my other machine (node 6.11.0), I cloned the demo just yesterday, and had no stylus errors there.

```
Errors prevented startup:                                                    
                                                                             
While loading plugin `vue-component-stylus` from package                     
`akryum:vue-stylus`:                                                         
native: Error parsing                                                        
C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin.
-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_module
ax\package.json:                                                             
Unexpected token                                                             
at Object.parse (native)                                                     
at readPackage (module.js:81:52)                                             
at tryPackage (module.js:91:13)                                              
at Function.Module._findPath (module.js:153:20)                              
at Function.Module._resolveFilename (module.js:323:25)                       
at Function.Module._load (module.js:276:25)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\functions\image.js:17:11)                                         
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\functions\index.js:15:13)                                         
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\visitor\evaluator.js:18:12)                                       
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\nodes\node.js:12:17)                                              
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\nodes\index.js:12:16)                                             
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\lexer.js:13:13)                                                   
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\parser.js:11:13)                                                  
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\renderer.js:12:14)                                                
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\lib\stylus.js:11:16)                                                  
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at Object.<anonymous>                                                        
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\vue-component-stylus\node_modul
stylus\index.js:4:5)                                                         
at Module._compile (module.js:409:26)                                        
at Object.Module._extensions..js (module.js:416:10)                          
at Module.load (module.js:343:32)                                            
at Module.Mp.load (C:\tools\tool-env\install-runtime.js:30:27)               
at Function.Module._load (module.js:300:12)                                  
at Module.require (module.js:353:17)                                         
at require (internal/module.js:12:17)                                        
at npmRequire (C:\tools\isobuild\bundler.js:1960:14)                         
at Module.Mp.useNode (packages/modules-runtime.js:527:20)                    
at fileEvaluate (packages/modules-runtime.js:196:20)                         
at Module.require (packages/modules-runtime.js:120:16)                       
at Module.Mp.importSync                                                      
(C:\Users\a_agr\AppData\Local\.meteor\packages\akryum_vue-stylus\0.0.5\plugin
e-component-stylus.os\npm\node_modules\meteor\modules\node_modules\reify\lib\
time.js:82:24)                                                               
at meteorInstall.node_modules.meteor.vue-component-stylus.vue-stylus.js      
(packages/vue-component-stylus/vue-stylus.js:1:147)                          
at fileEvaluate (packages/modules-runtime.js:197:9)                          
at require (packages/modules-runtime.js:120:16)                              
at <runJavaScript-20>:263:1                                                  
at <runJavaScript-20>:269:3                                               
```

**Comment by Akryum** [comment]
So you are using Meteor 1.6 beta right? (Didn't try it yet)
