### ISSUE TITLE
While loading plugin `vue-component` from package `akryum:vue-component`: module.js:547:15: Cannot find module

### ISSUE THREAD

**Issue by yosiah** [Akryum/vue-meteor-demo#31]
i get [vue-meteor-demo] - "fix: update deps and demos" on 2018-10-09.

at now (2018-10-27), new update meteor 1.8 and mongdb 4(to support multi document transaction)

and so i go to "meteor update" to "1.8".
success update , but server start error.

pl, check it 
thank you.
ref) may be this same problem
[while loading plugin vue-componen from package akyrum:vue-component, Cannot find module](https://stackoverflow.com/q/52875507/6881160)

---------------------------------------------
C:\meteor\vue-meteor-demo>meteor
[[[[[ C:\meteor\vue-meteor-demo ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3003.
=> Errors prevented startup:

   While loading plugin `vue-component` from package `akryum:vue-component`:
   module.js:547:15: Cannot find module
   'C:\Users\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\@babel\runtime\helpers\builtin\interopRequireDefault'
   at Function.Module._resolveFilename (module.js:547:15)
   at Function.Module._load (module.js:474:25)
   at Module.require (module.js:596:17)
   at require (internal/module.js:11:18)
   at Object.require (C:\tools\isobuild\bundler.js:2083:22)
   at makeInstallerOptions.fallback (packages/modules-runtime.js:653:18)
   at require (packages/modules-runtime.js:244:16)
   at tag-handler.js (<runJavaScript-33>:623:30)
   at fileEvaluate (packages/modules-runtime.js:339:7)
   at require (packages/modules-runtime.js:238:16)
   at <runJavaScript-33>:2236:1
   at <runJavaScript-33>:2243:3

=> Your application has errors. Waiting for file change.
=> Started MongoDB.
---------------------------------------------

and  ["WIP" mode] on Meteor 1.8, 
new "meteor create" and "meteor add akryum:vue-component"
same error, too.

**Comment by Akryum** [comment]
I guess you need to install `@babel/runtime` or similar issue.
