### ISSUE TITLE
Demo works with latest Meteor and Vue-Component packages despite lots of errors in log

### ISSUE THREAD

**Issue by DirkStevens** [Akryum/vue-meteor-demo#32]
Clone the project

`meteor update`
`meteor update --all-packages`
`meteor npm install`
`meteor run`

`dirkstevens@Retro ~/D/vue-meteor-demo-master> meteor run
[[[[[ ~/Downloads/vue-meteor-demo-master ]]]]]

=> Started proxy.
=> [HMR] Dev server listening on port 3003.
Compiling /Users/dirkstevens/Downloads/vue-meteor-demo-master/src/imports/ui/Apollo.vue with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:128:30)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:540:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:549:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:74:9)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:74:9)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
    at Object.eachLimit$1 (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
    at __bottom_mark__ (/tools/utils/parse-stack.js:69:14)
    at /tools/isobuild/compiler-plugin.js:198:27
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Profile.time (/tools/isobuild/compiler-plugin.js:185:22)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:184:15
    at Function._.each._.forEach (/Users/dirkstevens/.meteor/packages/meteor-tool/.1.8.0.11zn2tw.7g5h++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:174:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1102:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:835:34)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3115:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3266:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3220:14
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3096:31)
    at files.withCache (/tools/isobuild/bundler.js:3041:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3041:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12
Compiling src/imports/ui/GoogleMap.vue with meteor-babel without a cache
[object Object]
    at Object.exports.compile (/Users/dirkstevens/.meteor/packages/akryum_vue-coffee/.0.4.1.1jchfz2.nlqa++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component-coffee.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:77:13)
    at Object.compile (packages/babel-compiler.js:44:29)
    at packages/babel-compiler.js:198:22
    at Function.time (/tools/tool-env/profile.js:305:10)
    at profile (packages/babel-compiler.js:246:20)
    at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:197:20)
    at CoffeeScriptCompiler.compileOneFile (packages/coffeescript-compiler/coffeescript-compiler.js:79:26)
    at packages/vue-component-coffee/vue-coffee.js:19:46
    at packages/meteor.js:261:21
    at VueComponentTagHandler.getResults (packages/vue-component/plugin/tag-handler.js:91:26)
    at compileTags (packages/vue-component/plugin/vue-compiler.js:540:18)
    at compileOneFileWithContents (packages/vue-component/plugin/vue-compiler.js:549:12)
    at VueCompo.compileOneFile (packages/vue-component/plugin/vue-compiler.js:137:12)
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:54:34)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:71:11)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:74:9)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:983:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:958:16
    at async.eachLimit (packages/vue-component/plugin/vue-compiler.js:74:9)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3096:16
    at replenish (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:998:17)
    at /Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:1002:9
    at Object.eachLimit$1 (/Users/dirkstevens/.meteor/packages/akryum_vue-component/.0.14.1.aslzhk.fy4ou++os+web.browser+web.browser.legacy+web.cordova/plugin.vue-component.os/npm/node_modules/meteor/vue-component/node_modules/async/dist/async.js:3182:24)
    at VueCompo.processFilesForTarget (packages/vue-component/plugin/vue-compiler.js:38:11)
    at __bottom_mark__ (/tools/utils/parse-stack.js:69:14)
    at /tools/isobuild/compiler-plugin.js:198:27
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at Profile.time (/tools/isobuild/compiler-plugin.js:185:22)
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:184:15
    at Function._.each._.forEach (/Users/dirkstevens/.meteor/packages/meteor-tool/.1.8.0.11zn2tw.7g5h++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:174:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:1102:22)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:835:34)
    at /tools/utils/buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:829:18)
    at /tools/isobuild/bundler.js:3115:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3266:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3220:14
    at /tools/utils/buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:3096:31)
    at files.withCache (/tools/isobuild/bundler.js:3041:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3041:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12
=> Started MongoDB.
W20181118-20:51:44.382(1)? (STDERR) The version of @babel/runtime installed in your node_modules directory
W20181118-20:51:44.728(1)? (STDERR) (7.0.0-beta.55) is out of date. Please upgrade it by running
W20181118-20:51:44.729(1)? (STDERR)
W20181118-20:51:44.729(1)? (STDERR)   meteor npm install --save @babel/runtime@latest
W20181118-20:51:44.730(1)? (STDERR)
W20181118-20:51:44.730(1)? (STDERR) in your application directory.
W20181118-20:51:44.731(1)? (STDERR)
I20181118-20:51:45.628(1)? tracker installed
=> Started your app.

=> App running at: http://localhost:3000/`

**Comment by DirkStevens** [comment]
My own project does not recover from the above errors, but then again, it uses Blaze as well and not static-html as in this demo.

**Comment by Akryum** [comment]
I don't have those errors when running the demo
