### ISSUE TITLE
Get error of `import less file` (METEOR@1.8.1)????

### ISSUE THREAD

**Issue by thearabbit** [Akryum/vue-meteor-demo#34]
I clone new from this.
Get error after new clone, and run
``js
While checking for akryum:vue-pug@0.1.2:
   error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

=> Your application has errors. Waiting for file change.
=> Started MongoDB. catalog
```

**Comment by thearabbit** [comment]
After I update `meteor npm update, meteor update`, get the error
```js
=> Started proxy.
=> [HMR] Dev server listening on port 3003.
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
=> Started MongoDB.
I20190516-15:43:06.146(7)? tracker installed
W20190516-15:43:06.203(7)? (STDERR) /Users/theara/.meteor/packages/meteor-tool/.1.8.1.1hhzhrf.rnu8++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190516-15:43:06.204(7)? (STDERR) 						throw(ex);
W20190516-15:43:06.204(7)? (STDERR) 						^
W20190516-15:43:06.204(7)? (STDERR)
W20190516-15:43:06.204(7)? (STDERR) Error: Cannot find module './ui/App.vue'
W20190516-15:43:06.205(7)? (STDERR)     at makeMissingError (packages/modules-runtime.js:222:12)
W20190516-15:43:06.205(7)? (STDERR)     at Module.require (packages/modules-runtime.js:241:17)
W20190516-15:43:06.205(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:06.205(7)? (STDERR)     at app.js (src/imports/app.js:1:1)
W20190516-15:43:06.205(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:06.205(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:06.206(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:06.206(7)? (STDERR)     at server.js (src/imports/server.js:1:1)
W20190516-15:43:06.217(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:06.217(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:06.217(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:06.218(7)? (STDERR)     at index.js (src/index.js:1:8)
W20190516-15:43:06.218(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:06.218(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:06.218(7)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190516-15:43:06.218(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/app/app.js:1619:1
W20190516-15:43:06.218(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:419:36
W20190516-15:43:06.219(7)? (STDERR)     at Array.forEach (<anonymous>)
W20190516-15:43:06.219(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:228:19
W20190516-15:43:06.219(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:479:5
W20190516-15:43:06.219(7)? (STDERR)     at Function.run (/Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/profile.js:510:12)
W20190516-15:43:06.219(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:478:11
=> Exited with code: 1
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
I20190516-15:43:09.018(7)? tracker installed /
W20190516-15:43:09.072(7)? (STDERR) /Users/theara/.meteor/packages/meteor-tool/.1.8.1.1hhzhrf.rnu8++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190516-15:43:09.072(7)? (STDERR) 						throw(ex);
W20190516-15:43:09.073(7)? (STDERR) 						^
W20190516-15:43:09.073(7)? (STDERR)
W20190516-15:43:09.073(7)? (STDERR) Error: Cannot find module './ui/App.vue'
W20190516-15:43:09.073(7)? (STDERR)     at makeMissingError (packages/modules-runtime.js:222:12)
W20190516-15:43:09.073(7)? (STDERR)     at Module.require (packages/modules-runtime.js:241:17)
W20190516-15:43:09.074(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:09.074(7)? (STDERR)     at app.js (src/imports/app.js:1:1)
W20190516-15:43:09.074(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:09.074(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:09.075(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:09.075(7)? (STDERR)     at server.js (src/imports/server.js:1:1)
W20190516-15:43:09.075(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:09.075(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:09.075(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:09.076(7)? (STDERR)     at index.js (src/index.js:1:8)
W20190516-15:43:09.076(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:09.076(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:09.076(7)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190516-15:43:09.077(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/app/app.js:1619:1
W20190516-15:43:09.077(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:419:36
W20190516-15:43:09.077(7)? (STDERR)     at Array.forEach (<anonymous>)
W20190516-15:43:09.077(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:228:19
W20190516-15:43:09.077(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:479:5
W20190516-15:43:09.078(7)? (STDERR)     at Function.run (/Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/profile.js:510:12)
W20190516-15:43:09.078(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:478:11
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
=> Exited with code: 1
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
I20190516-15:43:13.172(7)? tracker installed \
W20190516-15:43:13.227(7)? (STDERR) /Users/theara/.meteor/packages/meteor-tool/.1.8.1.1hhzhrf.rnu8++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190516-15:43:13.227(7)? (STDERR) 						throw(ex);
W20190516-15:43:13.227(7)? (STDERR) 						^
W20190516-15:43:13.228(7)? (STDERR)
W20190516-15:43:13.228(7)? (STDERR) Error: Cannot find module './ui/App.vue'
W20190516-15:43:13.228(7)? (STDERR)     at makeMissingError (packages/modules-runtime.js:222:12)
W20190516-15:43:13.228(7)? (STDERR)     at Module.require (packages/modules-runtime.js:241:17)
W20190516-15:43:13.228(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:13.229(7)? (STDERR)     at app.js (src/imports/app.js:1:1)
W20190516-15:43:13.229(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:13.229(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:13.229(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:13.229(7)? (STDERR)     at server.js (src/imports/server.js:1:1)
W20190516-15:43:13.229(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:13.230(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:13.230(7)? (STDERR)     at Module.moduleLink [as link] (/Users/theara/.meteor/packages/modules/.0.13.0.1v462dq.d5l5++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
W20190516-15:43:13.230(7)? (STDERR)     at index.js (src/index.js:1:8)
W20190516-15:43:13.230(7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190516-15:43:13.231(7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190516-15:43:13.231(7)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190516-15:43:13.231(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/app/app.js:1619:1
W20190516-15:43:13.231(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:419:36
W20190516-15:43:13.231(7)? (STDERR)     at Array.forEach (<anonymous>)
W20190516-15:43:13.232(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:228:19
W20190516-15:43:13.232(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:479:5
W20190516-15:43:13.232(7)? (STDERR)     at Function.run (/Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/profile.js:510:12)
W20190516-15:43:13.232(7)? (STDERR)     at /Volumes/DATA/MeteorApp/vue-meteor-demo/.meteor/local/build/programs/server/boot.js:478:11
{ [Error: Unknown import (file not found): transitions]
  message: 'Unknown import (file not found): transitions',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/style/main.less',
  index: 20,
  line: 3,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "transitions";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/AppNav.vue',
  index: 33,
  line: 34,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
{ [Error: Unknown import (file not found): style/imports]
  message: 'Unknown import (file not found): style/imports',
  stack: undefined,
  type: 'File',
  filename: '/Volumes/DATA/MeteorApp/vue-meteor-demo/src/imports/ui/Cart.vue',
  index: 34,
  line: 35,
  column: 0,
  callLine: NaN,
  callExtract: undefined,
  extract: [ '', '@import "style/imports";', '' ] }
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by thearabbit** [comment]
I tried to change import less file, it work fine
```js
@import "./style/imports.less";
----
@import "imports.less";
```

**Comment by bedinsky** [comment]
I've got the similar issues but in file "src/imports/ui/AppNav.vue" I read
@import "style/imports";
Is this error related to less preprocessor ? after npm install I did not see any less, less-loader folder in node_modules ? Any help is appreciated

**Comment by Thaumonaut** [comment]
I had the same issue so these were the changes I made to get it working.

Before

main.less: 
```
@import "imports";
@import "transitions";
```
transitions.less: 
`@import "imports";` 

Cart.vue: 
`@import "style/imports";`

AppNav.vue: 
`@import "style/imports";`

----
After

main.less: 
```
@import "imports.less";
@import "transitions.less";
```
transitions.less: 
`@import "imports.less";`

Cart.vue: 
`@import "./style/imports.less";`

AppNav.vue: 
 `@import "./style/imports.less";`

**Comment by Akryum** [comment]
This will be fixed in the upcoming release of `vue-component`.
