### ISSUE TITLE
Register is not a function

### ISSUE THREAD

**Issue by ghost** [Akryum/vue-meteor-demo#4]
Hi . I cloned your repository and did a `meteor npm i` and ran `meteor`. But it gives me this error

```
06-13:04:16.233(8)? (STDERR) TypeError: register is not a function
W20170606-13:04:16.233(8)? (STDERR)     at meteorInstall.src.imports.supply.index.js (src/imports/supply/index.js:4:1)
W20170606-13:04:16.233(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170606-13:04:16.234(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170606-13:04:16.234(8)? (STDERR)     at meteorInstall.src.imports.app.js (src/imports/app.js:1:91)
W20170606-13:04:16.234(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170606-13:04:16.235(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170606-13:04:16.235(8)? (STDERR)     at meteorInstall.src.imports.server.js (src/imports/server.js:1:154)
W20170606-13:04:16.235(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170606-13:04:16.235(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170606-13:04:16.236(8)? (STDERR)     at meteorInstall.src.index.js (src/index.js:1:14)

```

How can I fix this? Thanks. I also installed vue-supply but still no avail

**Comment by ghost** [comment]
Updating `vue-supply` did it for me. Made a PR for this
